name: docs

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          mamba-version: '*'
          channels: conda-forge,defaults
          activate-environment: "compas_ppc-dev"
          environment-file: environment.yml
          
      - name: Build C++ extensions
        shell: bash -el {0}
        run: |
          python -m pip install -e .
          
      - uses: compas-dev/compas-actions.docs@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          use_conda: false  # We've already set up conda ourselves
          test_docs: false
          doc_url: "https://github.com//compas_ppc"